name: Release version
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 16
          distribution: 'adopt'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Package OBSStamper
        run: ./gradlew --stacktrace shadowJar
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: build/libs/OBSStamper-*.jar

  create-streamdeck-resources:
    name: Prepare Streamdeck package resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Replace version in bat
        run: sed -i "s/<version>/${{ steps.version.outputs.version }}/" deploy/OBSStamper.bat
      - name: Upload Streamdeck resources
        uses: actions/upload-artifact@v3
        with:
          name: streamdeck
          path: deploy

  upload-artifact:
    name: Zip and upload artefact
    runs-on: ubuntu-latest
    needs:
      - build
      - create-streamdeck-resources
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: build/libs/
      - name: Download streamdeck resources
        uses: actions/download-artifact@v3
        with:
          name: streamdeck
          path: deploy/
      - name: Zip Streamdeck files
        uses: montudor/action-zip@v1
        with:
          args: zip -j -r OBSStamper-Streamdeck.zip build/libs/OBSStamper-*.jar deploy
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/OBSStamper-*.jar
            OBSStamper-Streamdeck.zip
